version: "3.7"
services:
  app:
    build:
      context: .
      target: production
    image: example
    container_name: app
    volumes:
      - ${PWD}:/example
    working_dir: /example
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

